name: Docker

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: zingimmick/elasticsearch-ik # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag

      - id: elasticsearch_version
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=$(curl -s -S 'https://registry.hub.docker.com/v2/repositories/elastic/elasticsearch/tags/' | sed -e 's/,/,\n/g' -e 's/\[/\[\n/g' | grep '"name"' | awk -F\" '{print $4;}' | tac | tail -n1)

          # Check plugin version
          PLUGIN_VERSION=$(git ls-remote --tags --sort="v:refname" git://github.com/medcl/elasticsearch-analysis-ik.git | tail -n1 | sed 's/.*\///' | sed -e 's/^v//')
          [ "$VERSION" != "$PLUGIN_VERSION" ] && echo "::warning::Elasticsearch $VERSION is now available and Plugin [analysis-ik] was only built for Elasticsearch $PLUGIN_VERSION" && VERSION=$PLUGIN_VERSION

          echo "::set-output name=elasticsearch_version::$VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: zingimmick/elasticsearch-ik:${{ steps.elasticsearch_version.outputs.elasticsearch_version }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            ELASTICSEARCH_VERSION=${{ steps.elasticsearch_version.outputs.elasticsearch_version }}
