# This is a basic workflow to help you get started with Actions

name: Sync Tag From medcl/elasticsearch-analysis-ik

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          TAGS=$(git ls-remote --tags --sort="v:refname" git://github.com/medcl/elasticsearch-analysis-ik.git | sed 's/.*\///' | sed -e 's/^v//' | xargs)
          for TAG in $TAGS; do
            git ls-remote --tags --exit-code git://github.com/zingimmick/elasticsearch-ik.git v"$TAG"
            if [[ $? == 2 ]]; then
              echo v"$TAG"
            fi
          done
